#数据源基本配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#redis配置
  redis:
    host: localhost
    password: 123456
#RabbitMQ
  rabbitmq:
    host: 192.168.83.133
    username: guest
    password: guest
    port: 5672
#elasticsearch
  elasticsearch:
    jest:
      uris: http://192.168.83.133:9200
  mail:
    host: smtp.qq.com
    username: xxxxxx@qq.com
    password: 123456
    #QQ邮箱需要额外的ssl安全连接
    properties.mail.smtp.ssl.enable: true


#mybatis配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

#tomcat配置
server:
  port: 8081

#日志等级
#debug: true






